### ISSUE TITLE
tslint gulp task fails

### ISSUE THREAD

**Issue by afoo** [Microsoft/cordova-plugin-code-push#294]
### Description

I cloned the repository, did `npm install`, then `gulp`. After fixing the TS compile error (see  pull request #293), the `tslint` task fails with the following error:

```
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

TypeError: ruleConfiguration.forEach is not a function
    at Object.convertRuleOptions (/Users/jan/src/cordova-plugin-code-push/node_modules/tslint/lib/configuration.js:426:23)
    at Linter.getEnabledRules (/Users/jan/src/cordova-plugin-code-push/node_modules/tslint/lib/linter.js:194:47)
    at Linter.lint (/Users/jan/src/cordova-plugin-code-push/node_modules/tslint/lib/linter.js:74:33)
    at /Users/jan/src/cordova-plugin-code-push/node_modules/gulp-tslint/index.js:102:16
    at wrappedMapper (/Users/jan/src/cordova-plugin-code-push/node_modules/map-stream/index.js:83:19)
    at Stream.stream.write (/Users/jan/src/cordova-plugin-code-push/node_modules/map-stream/index.js:95:21)
    at write (/Users/jan/src/cordova-plugin-code-push/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/jan/src/cordova-plugin-code-push/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/jan/src/cordova-plugin-code-push/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:105:13)
```
### Reproduction

* `git clone git@github.com:Microsoft/cordova-plugin-code-push.git`
* `cd cordova-plugin-code-push`
* `npm install`
* `gulp`

### Additional Information

* cordova-plugin-code-push version: 726d6ffe6b91e27ca04da3b350b828f8a8be9508
* List of installed plugins: N/A
* Cordova version: 7.0.1
* iOS/Android/Windows version: macOS 10.12.6
* npm version: 5.3.0
* tslint version: 5.7.0

**Comment by sergey-akhalkov** [comment]
Hi @afoo, thanks for reaching us - the issue has been fixed in https://github.com/Microsoft/cordova-plugin-code-push/commit/ba61bc3a6b62cb4235dd46fe8f0fec2b2e02a950 - please verify and feel free to reopen in case of any issues or questions.
