### ISSUE TITLE
Cordova FileTransfer/FileUtils Error with PhonegapBuild

### ISSUE THREAD

**Issue by Zavorotyuk** [Microsoft/cordova-plugin-code-push#322]
### Description

Android build fails after installing cordova-plugin-code-push.

### Additional Information

* cordova-plugin-code-push version: 1.10.0-beta
* List of installed plugins:
  https://github.com/sarriaroman/photoviewer.git 1.1.1 
  https://github.com/Telerik-Verified-Plugins/Facebook.git 1.7.1.
  https://github.com/MBuchalik/cordova-build-architecture.git v1.0.1 
  cordova-custom-config 3.1.2 
  cordova-plugin-badge 0.8.5 
  cordova-plugin-camera 2.4.1
  cordova-plugin-canvas2image 0.7.0 
  cordova-plugin-code-push 1.10.0-beta 
  cordova-plugin-contacts 2.2.1
  cordova-plugin-crosswalk-webview 2.3.0
  https://github.com/EddyVerbruggen/Custom-URL-scheme.git 4.3.0 
  cordova-plugin-device 1.1.6 
  cordova-plugin-email-composer 0.8.3
  cordova-plugin-geolocation 2.4.3
  cordova-plugin-google-analytics 1.8.3
  cordova-plugin-googleplus latest
  cordova-plugin-inappbrowser 1.7.1 
  cordova-plugin-network-information 1.3.3 
  cordova-plugin-statusbar 2.2.3 
  cordova-plugin-whitelist 1.3.2 
  cordova-plugin-x-socialsharing 5.2.1 
  cordova.plugins.diagnostic 3.4.1
  de.appplant.cordova.plugin.printer latest 
  ionic-plugin-keyboard 2.2.1
  onesignal-cordova-plugin 2.1.2
  phonegap-plugin-barcodescanner 6.0.5 

* Phonegap cli version: 7.0.1
* iOS/Android/Windows version: ios - 4.4.0  android - 6.2.3
* Reproduce on bouth debug and release builds

```bash
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Configuration on demand is an incubating feature.
:wrapper

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Configuration on demand is an incubating feature.
null
org.xwalk:xwalk_core_library:23+
Incremental java compilation is an incubating feature.
:cdvCreateAssetManifest
:preBuild
:preArmv7DebugBuild
:checkArmv7DebugManifest
:preArmv7ReleaseBuild
:preX86DebugBuild
:preX86ReleaseBuild
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareBarcodescannerLibrary
:prepareComAndroidSupportAnimatedVectorDrawable2600Alpha1Library
:prepareComAndroidSupportAppcompatV72600Alpha1Library
:prepareComAndroidSupportCardviewV72321Library
:prepareComAndroidSupportCustomtabs2400Library
:prepareComAndroidSupportSupportCompat2600Alpha1Library
:prepareComAndroidSupportSupportCoreUi2600Alpha1Library
:prepareComAndroidSupportSupportCoreUtils2600Alpha1Library
:prepareComAndroidSupportSupportFragment2600Alpha1Library
:prepareComAndroidSupportSupportMediaCompat2600Alpha1Library
:prepareComAndroidSupportSupportV42600Alpha1Library
:prepareComAndroidSupportSupportVectorDrawable2600Alpha1Library
:prepareComCommit451PhotoView124Library
:prepareComFacebookAndroidFacebookAndroidSdk4110Library
:prepareComGoogleAndroidGmsPlayServicesAnalytics1104Library
:prepareComGoogleAndroidGmsPlayServicesAnalyticsImpl1104Library
:prepareComGoogleAndroidGmsPlayServicesAuth1104Library
:prepareComGoogleAndroidGmsPlayServicesAuthBase1104Library
:prepareComGoogleAndroidGmsPlayServicesBase1104Library
:prepareComGoogleAndroidGmsPlayServicesBasement1104Library
:prepareComGoogleAndroidGmsPlayServicesGcm1104Library
:prepareComGoogleAndroidGmsPlayServicesIdentity1104Library
:prepareComGoogleAndroidGmsPlayServicesIid1104Library
:prepareComGoogleAndroidGmsPlayServicesLocation1104Library
:prepareComGoogleAndroidGmsPlayServicesTagmanagerV4Impl1104Library
:prepareComGoogleAndroidGmsPlayServicesTasks1104Library
:prepareComOnesignalOneSignal357Library
:prepareMeLeolinShortcutBadger1119Library
:prepareOrgApacheCordovaCordovaLib623DebugLibrary
:prepareOrgXwalkXwalk_core_library23535894Library
:prepareArmv7DebugDependencies
:compileArmv7DebugAidl
:compileArmv7DebugRenderscript
:generateArmv7DebugBuildConfig
:mergeArmv7DebugShaders
:compileArmv7DebugShaders
:generateArmv7DebugAssets
:mergeArmv7DebugAssets
:createXwalkCommandLineFileArmv7Debug
:generateArmv7DebugResValues
:generateArmv7DebugResources
:mergeArmv7DebugResources
:processArmv7DebugManifest
:processArmv7DebugResources
:generateArmv7DebugSources
:incrementalArmv7DebugJavaCompilationSafeguard
:compileArmv7DebugJavaWithJavac
:compileArmv7DebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/project/src/org/apache/cordova/filetransfer/FileTransfer.java:49: error: package org.apache.cordova.file does not exist
import org.apache.cordova.file.FileUtils;
                              ^
/project/src/org/apache/cordova/filetransfer/FileTransfer.java:851: error: cannot find symbol
                        FileUtils filePlugin = (FileUtils) pm.getPlugin("File");
                        ^
  symbol: class FileUtils
/project/src/org/apache/cordova/filetransfer/FileTransfer.java:851: error: cannot find symbol
                        FileUtils filePlugin = (FileUtils) pm.getPlugin("File");
                                                ^
  symbol: class FileUtils
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
:compileArmv7DebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7DebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.783 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/project/src/org/apache/cordova/filetransfer/FileTransfer.java:49: error: package org.apache.cordova.file does not exist
import org.apache.cordova.file.FileUtils;
                              ^
/project/src/org/apache/cordova/filetransfer/FileTransfer.java:851: error: cannot find symbol
                        FileUtils filePlugin = (FileUtils) pm.getPlugin("File");
                        ^
  symbol: class FileUtils
/project/src/org/apache/cordova/filetransfer/FileTransfer.java:851: error: cannot find symbol
                        FileUtils filePlugin = (FileUtils) pm.getPlugin("File");
                                                ^
  symbol: class FileUtils
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7DebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by ruslan-bikkinin** [comment]
Hi @Zavorotyuk and sorry for late response. I am able to pick it up now, so I will let you know about the progress.

**Comment by ruslan-bikkinin** [comment]
@Zavorotyuk I tried to reproduced the issue but was able to build application using plugins list you provided. Could you take a look at it and compare your config/environment with the ones I've been used?
Here is the [link](https://github.com/ruslan-bikkinin/cordova322) to the sample app repo.

My environment:
```console
rbikkinin@rbikkinin-work:/work/support/cordova322$ phonegap --version
7.0.1
rbikkinin@rbikkinin-work:/work/support/cordova322$ cordova --version
6.5.0
rbikkinin@rbikkinin-work:/work/support/cordova322$ phonegap build android
[phonegap] executing 'cordova build android ' ...
[phonegap] completed 'cordova build android --no-telemetry'
```

**Comment by Zavorotyuk** [comment]
@ruslan-bikkinin I don't use a local environment to build the application but send it to https://build.phonegap.com/ instead. So i don't even have phonegap installed on my machine.

**Comment by Whebcraft** [comment]
try building with <plugin name="cordova-plugin-file-transfer" spec="~1.6.1"/>

**Comment by Zavorotyuk** [comment]
@Whebcraft It really helped. Thank you, you saved a lot of my time.

**Comment by ruslan-bikkinin** [comment]
@Zavorotyuk did the solution @Whebcraft provided resolve your issue?

**Comment by Zavorotyuk** [comment]
@ruslan-bikkinin Yes, it did

**Comment by levarberry** [comment]
I was having this problem...   and to fix it  I simply removed  cordova-plugin-file   and then reinstalled it.   You will need to add --force to remove it... but that's ok, because you're putting it right back.

**Comment by NadGu** [comment]
Hi, I am having the same problem, with the same error output. I have removed and re-added the plugin many times but nothing changes.
`Installed platforms:
  android 6.2.3
  ios 4.3.1
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  webos ~3.7.0
  windows ~4.4.0
  wp8 ~3.8.2 (deprecated)
`

**Comment by NadGu** [comment]
I am haveing the same problem with the same error output. I have tried what @Whebcraft adviced -didn't work. I removed and re-added the plugin in the project multiple times -didn't work. Removed the android platform and added the 6.3.0 -didn't worked. Nothing changes; always the same error output. 
Can someone help me?
