### ISSUE TITLE
Plugin 'File' not found, or is not a CDVPlugin.

### ISSUE THREAD

**Issue by adriano-di-giovanni** [Microsoft/cordova-plugin-code-push#366]
On iOS, app initialization fails with

```
2018-02-12 10:01:02.615105+0100 Code Push Example[12738:4924563] CDVPlugin class CDVFile (pluginName: File) does not exist.
2018-02-12 10:01:02.615233+0100 Code Push Example[12738:4924563] ERROR: Plugin 'File' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2018-02-12 10:01:02.615363+0100 Code Push Example[12738:4924563] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["File1964347700","File","requestAllPaths",[]]
```

I created a blank application and installed `cordova-plugin-code-push`. Please, find the log for the plugin installation below:

```
Installing "cordova-plugin-code-push" for ios
Installing "code-push" for ios
Installing "cordova-plugin-dialogs" for ios
Installing "cordova-plugin-device" for ios
Detecting cordova version...
Cordova version is 8.0.0
Installing the latest version of file-transfer plugin... 
Adding cordova-plugin-code-push to package.json
Saved plugin info for "cordova-plugin-code-push" to config.xml
````
Please, find the `config.xml` and `package.json` for the application below:

```xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.adrianodigiovanni.codepushexample" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Code Push Example</name>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="*" />
    <preference name="CodePushDeploymentKey" value="L2y36S47jnoObAoJzB9Wqn6SKu2yecc69990-f55a-4438-baad-23a470c8665a" />
    <plugin name="cordova-plugin-file-transfer" spec="^1.7.1" />
    <plugin name="cordova-plugin-zip" spec="^3.1.0" />
    <plugin name="cordova-plugin-code-push" spec="^1.11.3" />
    <engine name="ios" spec="^4.5.4" />
</widget>
```

```json
{
  "name": "com.adrianodigiovanni.codepushexample",
  "displayName": "Code Push Example",
  "version": "1.0.0",
  "description": "A sample Apache Cordova application that responds to the deviceready event.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Apache Cordova Team",
  "license": "Apache-2.0",
  "dependencies": {
    "code-push": "^2.0.4",
    "cordova-ios": "^4.5.4",
    "cordova-plugin-code-push": "^1.11.3",
    "cordova-plugin-device": "^2.0.1",
    "cordova-plugin-dialogs": "^2.0.1",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-zip": "^3.1.0"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-zip": {},
      "cordova-plugin-code-push": {}
    },
    "platforms": [
      "ios"
    ]
  }
}
```

Please, find the complete stack trace below:

```
2018-02-12 10:01:01.329082+0100 Code Push Example[12738:4924563] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///Users/me/Library/Developer/CoreSimulator/Devices/CDAB7DE2-7216-4A19-BEAD-80A72F368535/data/Containers/Data/Application/17EE4CEB-FCDF-43B4-9B6D-A8A4C249DA20/Library/Cookies/com.adrianodigiovanni.codepushexample.binarycookies
2018-02-12 10:01:01.443357+0100 Code Push Example[12738:4924563] Apache Cordova native platform version 4.5.3 is starting.
2018-02-12 10:01:01.444139+0100 Code Push Example[12738:4924563] Multi-tasking -> Device: YES, App: YES
2018-02-12 10:01:01.450860+0100 Code Push Example[12738:4924563] 

Started backup to iCloud! Please be careful.
Your application might be rejected by Apple if you store too much data.
For more information please read "iOS Data Storage Guidelines" at:
https://developer.apple.com/icloud/documentation/data-storage/
To disable web storage backup to iCloud, set the BackupWebStorage preference to "local" in the Cordova config.xml file
2018-02-12 10:01:01.591087+0100 Code Push Example[12738:4924563] [MC] Lazy loading NSBundle MobileCoreServices.framework
2018-02-12 10:01:01.592017+0100 Code Push Example[12738:4924563] [MC] Loaded MobileCoreServices.framework
2018-02-12 10:01:01.597099+0100 Code Push Example[12738:4924563] Using UIWebView
2018-02-12 10:01:01.598963+0100 Code Push Example[12738:4924563] [CDVTimer][console] 0.043988ms
2018-02-12 10:01:01.599175+0100 Code Push Example[12738:4924563] [CDVTimer][handleopenurl] 0.077963ms
2018-02-12 10:01:01.600051+0100 Code Push Example[12738:4924563] Unlimited access to network resources
2018-02-12 10:01:01.600447+0100 Code Push Example[12738:4924563] [CDVTimer][intentandnavigationfilter] 1.156092ms
2018-02-12 10:01:01.600614+0100 Code Push Example[12738:4924563] [CDVTimer][gesturehandler] 0.041008ms
2018-02-12 10:01:01.600718+0100 Code Push Example[12738:4924563] CDVPlugin class CDVFile (pluginName: file) does not exist.
2018-02-12 10:01:01.600837+0100 Code Push Example[12738:4924563] [CDVTimer][file] 0.110984ms
2018-02-12 10:01:01.602030+0100 Code Push Example[12738:4924563] [CDVTimer][codepush] 1.087070ms
2018-02-12 10:01:01.602131+0100 Code Push Example[12738:4924563] [CDVTimer][TotalPluginStartup] 3.255010ms
2018-02-12 10:01:02.091912+0100 Code Push Example[12738:4924563] Resetting plugins due to page load.
2018-02-12 10:01:02.539857+0100 Code Push Example[12738:4924563] Finished load of: file:///Users/me/Library/Developer/CoreSimulator/Devices/CDAB7DE2-7216-4A19-BEAD-80A72F368535/data/Containers/Bundle/Application/D83BAE84-2079-424D-9E82-DDAD7CDD2FE9/Code%20Push%20Example.app/www/index.html
2018-02-12 10:01:02.615105+0100 Code Push Example[12738:4924563] CDVPlugin class CDVFile (pluginName: File) does not exist.
2018-02-12 10:01:02.615233+0100 Code Push Example[12738:4924563] ERROR: Plugin 'File' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2018-02-12 10:01:02.615363+0100 Code Push Example[12738:4924563] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["File1964347700","File","requestAllPaths",[]]
```

The error occurs on the emulator. I did not test the app on a real device.

**Comment by iTOYS** [comment]
Hi @adriano-di-giovanni, thanks for reporting!
Do you have `plugins/cordova-plugin-file` folder in your project?
Could you please try to (re)install `cordova plugin add cordova-plugin-file` manually.
Any errors while installation? Does project work after that?

Thanks!

**Comment by adriano-di-giovanni** [comment]
Yes. It works. Do I have to explicitly install it? Is it intended behavior?

**Comment by iTOYS** [comment]
Actually we have `beforeInstall` script that should install it, and I don't know why it doesn't!
I'll investigate this, but I doesn't see any error while your installation.

**Comment by iTOYS** [comment]
@adriano-di-giovanni 

We've published 1.11.5 release, which contains some changes in installation hook.
Could you please check it?

Thanks!

**Comment by adriano-di-giovanni** [comment]
It doesn't work, yet.

This is the new trace

```
2018-02-14 14:52:28.025880+0100 Code Push Example[83474:6226875] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///Users/me/Library/Developer/CoreSimulator/Devices/CDAB7DE2-7216-4A19-BEAD-80A72F368535/data/Containers/Data/Application/3DD6FF82-5DD0-476E-ADD7-4D4CD5BA69BC/Library/Cookies/com.adrianodigiovanni.codepushexample.binarycookies
2018-02-14 14:52:28.075487+0100 Code Push Example[83474:6226875] Apache Cordova native platform version 4.5.3 is starting.
2018-02-14 14:52:28.075941+0100 Code Push Example[83474:6226875] Multi-tasking -> Device: YES, App: YES
2018-02-14 14:52:28.085391+0100 Code Push Example[83474:6226875] 

Started backup to iCloud! Please be careful.
Your application might be rejected by Apple if you store too much data.
For more information please read "iOS Data Storage Guidelines" at:
https://developer.apple.com/icloud/documentation/data-storage/
To disable web storage backup to iCloud, set the BackupWebStorage preference to "local" in the Cordova config.xml file
2018-02-14 14:52:28.659876+0100 Code Push Example[83474:6226875] [MC] Lazy loading NSBundle MobileCoreServices.framework
2018-02-14 14:52:28.660697+0100 Code Push Example[83474:6226875] [MC] Loaded MobileCoreServices.framework
2018-02-14 14:52:28.673371+0100 Code Push Example[83474:6226875] Using UIWebView
2018-02-14 14:52:28.674780+0100 Code Push Example[83474:6226875] [CDVTimer][console] 0.046015ms
2018-02-14 14:52:28.674983+0100 Code Push Example[83474:6226875] [CDVTimer][handleopenurl] 0.063896ms
2018-02-14 14:52:28.675909+0100 Code Push Example[83474:6226875] Unlimited access to network resources
2018-02-14 14:52:28.676340+0100 Code Push Example[83474:6226875] [CDVTimer][intentandnavigationfilter] 1.253009ms
2018-02-14 14:52:28.676498+0100 Code Push Example[83474:6226875] [CDVTimer][gesturehandler] 0.062108ms
2018-02-14 14:52:28.676625+0100 Code Push Example[83474:6226875] CDVPlugin class CDVFile (pluginName: file) does not exist.
2018-02-14 14:52:28.676715+0100 Code Push Example[83474:6226875] [CDVTimer][file] 0.108004ms
2018-02-14 14:52:28.677732+0100 Code Push Example[83474:6226875] [CDVTimer][codepush] 0.908017ms
2018-02-14 14:52:28.677832+0100 Code Push Example[83474:6226875] [CDVTimer][TotalPluginStartup] 3.144026ms
2018-02-14 14:52:30.069547+0100 Code Push Example[83474:6226875] Resetting plugins due to page load.
2018-02-14 14:52:32.209208+0100 Code Push Example[83474:6226875] Finished load of: file:///Users/me/Library/Developer/CoreSimulator/Devices/CDAB7DE2-7216-4A19-BEAD-80A72F368535/data/Containers/Bundle/Application/7DE04163-0E02-4E8A-9FF9-D8CAD846A671/Code%20Push%20Example.app/www/index.html
2018-02-14 14:52:32.278263+0100 Code Push Example[83474:6226875] CDVPlugin class CDVFile (pluginName: File) does not exist.
2018-02-14 14:52:32.278377+0100 Code Push Example[83474:6226875] ERROR: Plugin 'File' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2018-02-14 14:52:32.278537+0100 Code Push Example[83474:6226875] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["File51344706","File","requestAllPaths",[]]
```

Did you try to install your plugin on a fresh cordova project?

**Comment by iTOYS** [comment]
Sure, and all work fine.

**Comment by iTOYS** [comment]
@adriano-di-giovanni 
I've just published new version(1.11.7) of plugin, could you please check it and let me know any results?

**Comment by adriano-di-giovanni** [comment]
I'm very sorry but it doesn't work. Can I do more to help you?

**Comment by iTOYS** [comment]
Could you please write exactly all steps to reproduce:
```
$ cordova create app_name
...
...
...
```
And installation outputs.

Thanks!

**Comment by adriano-di-giovanni** [comment]
I haven't tried to reinstall on a clean project, yet.

I installed it on one of my apps and an error occurs:

```
Failed to install 'cordova-plugin-file-transfer': CordovaError: Version of installed plugin: "cordova-plugin-file@6.0.1" does not satisfy dependency plugin requirement "cordova-plugin-file@^4.0.0". Try --force to use installed plugin as dependency.
    at /Users/me/.nvm/versions/node/v6.12.2/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:557:37
    at _fulfilled (/Users/me/.nvm/versions/node/v6.12.2/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/me/.nvm/versions/node/v6.12.2/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/me/.nvm/versions/node/v6.12.2/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /Users/me/.nvm/versions/node/v6.12.2/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:509:49
    at flush (/Users/me/.nvm/versions/node/v6.12.2/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Failed to install 'cordova-plugin-code-push': CordovaError: Version of installed plugin: "cordova-plugin-file@6.0.1" does not satisfy dependency plugin requirement "cordova-plugin-file@^4.0.0". Try --force to use installed plugin as dependency.
    at /Users/me/.nvm/versions/node/v6.12.2/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:557:37
    at _fulfilled (/Users/me/.nvm/versions/node/v6.12.2/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/me/.nvm/versions/node/v6.12.2/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/me/.nvm/versions/node/v6.12.2/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /Users/me/.nvm/versions/node/v6.12.2/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:509:49
    at flush (/Users/me/.nvm/versions/node/v6.12.2/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Failed to restore plugin "cordova-plugin-code-push" from config.xml. You might need to try adding it again. Error: Version of installed plugin: "cordova-plugin-file@6.0.1" does not satisfy dependency plugin requirement "cordova-plugin-file@^4.0.0". Try --force to use installed plugin as dependency.
```

It seems to fail if cordova-plugin-file is already installed.

**Comment by iTOYS** [comment]
Yes, you should cleanup your project:
```
$ cordova plugin rm cordova-plugin-code-push --force
$ cordova plugin rm cordova-plugin-file-transfer --force
$ cordova plugin rm cordova-plugin-file --force
$ cordova plugin rm cordova-plugin-zip --force
```
And reinstall `cordova-plugin-code-push`:
```
$ cordova plugin cordova-plugin-code-push --force
```

**Comment by adriano-di-giovanni** [comment]
The project is clean but the file plugin is a direct dependency. I think it is a use case. That’s why I mention it. Do you really need such an old version of the file plugin?

Inviato da iPhone

**Comment by iTOYS** [comment]
Yes, since `cordova-plugin-file@5.0.0` it doesn't support `cordova-android@6.3.0` and lower.
We'd like to stay support both.

**Comment by adriano-di-giovanni** [comment]
I understand but I think you shouldn't lock the `cordova-plugin-file` version. Many plugins depend on it. The most notable one is `cordova-plugin-media`. If `cordova-plugin-code-push` works with newer versions of the `cordova-plugin-file` you should allow us to use those versions. Do you agree?

**Comment by lionelgaillard** [comment]
Hello @iTOYS ,

I also dont' think `cordova-plugin-code-push` has to force `cordova-plugin-file` version:
If you use `cordova-android@6.3.0` at the moment you install `cordova-plugin-code-push`, it will install the higher common supported version which is `4.3.3`... Right ? (at least it should)

More importantly, whatever the versions, is there still the need to use the `after_plugin_add` hook to add `cordova-plugin-file`, `cordova-plugin-file-transfer`, and `cordova-plugin-zip` ?

Can't they be normal dependencies in `plugin.xml` ?

I don't know why these dependencies have been moved from `plugin.xml` to `hooks/afterPluginAdd.js` in the first place, but I can't find any reason to keep them there now.

**Comment by alexandergoncharov** [comment]
Hi all,

@lionelgaillard, Thanks for reporting!

>If you use cordova-android@6.3.0 at the moment you install cordova-plugin-code-push, it will install the higher common supported version which is 4.3.3... Right ? (at least it should)

We also have case if we added plugin before platform. In this case it will not work.

> Can't they be normal dependencies in plugin.xml ?
If I understand correct - unfortunately no because `file` plugin require `file-transfer` and `zip` necessary version.
We also tried to use usual way for installing this plugins with hard fixed version: https://github.com/Microsoft/cordova-plugin-code-push/commit/70d0c5d316837ca4c8617455c5a363d331482479#diff-53f390d375398624afe1cfe1125f42bf
But this affects users who want use newest version of this plugins.

At now this is in hook because we would like to support newest and old version of android. Hook just installs this plugins like cli commands. In this case all functional will work Out-of-the-box and also provide possibility to updated plugins to newest versions if users prefer it.

@lionelgaillard Please feel free to provide better approach if you have it. =)
Hope it was helpful for you.

Thanks,
Alexander
