### ISSUE TITLE
Given CSP policy does not work with crosswalk

### ISSUE THREAD

**Issue by DavidGOrtega** [Microsoft/cordova-plugin-code-push#387]
### Description

My app uses cocoon.io webview+ (crosswalk) on Android. I have tried several configurations of the CSP from yours and/or other users, however I have always this result:

```codePushUtil.js:36 [CodePush] Checking for update.
codePushUtil.js:36 [CodePush] An update is available. {"appVersion":"0.0.1","deploymentKey":"VQ1sZ2eKMsxEZf6XVoC2C5VsK9q_HyBFrHL9z","downloadUrl":"https://codepushupdates.azureedge.net/storagev2/V0zHbovaLzuv8W6DYkPbP-qWgGGl937ddf99-6537-4af6-aadb-fefb12c30483","isMandatory":false,"label":"v2","packageHash":"fc91705d7a517be219b61a18e26dbe61eaf38d4197be0f921ece0fe775ab8309","packageSize":20145806,"failedInstall":false}
codePushUtil.js:36 [CodePush] Checking for update.
codePushUtil.js:36 [CodePush] Reported status: {"status":0,"appVersion":"0.0.1","deploymentKey":"VQ1sZ2eKMsxEZf6XVoC2C5VsK9q_HyBFrHL9z"}
codePushUtil.js:36 [CodePush] An update is available. {"appVersion":"0.0.1","deploymentKey":"VQ1sZ2eKMsxEZf6XVoC2C5VsK9q_HyBFrHL9z","downloadUrl":"https://codepushupdates.azureedge.net/storagev2/V0zHbovaLzuv8W6DYkPbP-qWgGGl937ddf99-6537-4af6-aadb-fefb12c30483","isMandatory":false,"label":"v2","packageHash":"fc91705d7a517be219b61a18e26dbe61eaf38d4197be0f921ece0fe775ab8309","packageSize":20145806,"failedInstall":false}
codePushUtil.js:36 [CodePush] Downloading update
codePushUtil.js:36 [CodePush] Package download success: {"deploymentKey":"VQ1sZ2eKMsxEZf6XVoC2C5VsK9q_HyBFrHL9z","label":"v2","appVersion":"0.0.1","isMandatory":false,"packageHash":"fc91705d7a517be219b61a18e26dbe61eaf38d4197be0f921ece0fe775ab8309","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/files/codepush/download/update.zip"}
codePushUtil.js:36 [CodePush] Installing update
codePushUtil.js:36 [CodePush] Applying full update
codePushUtil.js:41 [CodePush] Preinstall failure. Could not get the package start pageCodePushUtil.logError @ codePushUtil.js:41preInstallFailure @ localPackage.js:245callbackFromNative @ cordova.js:295processMessage @ cordova.js:1119processMessages @ cordova.js:1142
codePushUtil.js:41 [CodePush]  An error has occured while installing the package. Could not get the package start page. StackTrace: Error: An error has occured while installing the package. Could not get the package start page
    at preInstallFailure (file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/localPackage.js:246:41)
    at Object.callbackFromNative (file:///android_asset/www/cordova.js:295:52)
    at processMessage (file:///android_asset/www/cordova.js:1119:17)
    at processMessages (file:///android_asset/www/cordova.js:1142:9)CodePushUtil.logError @ codePushUtil.js:41CodePushUtil.invokeErrorCallback @ codePushUtil.js:45installError @ localPackage.js:43preInstallFailure @ localPackage.js:247callbackFromNative @ cordova.js:295processMessage @ cordova.js:1119processMessages @ cordova.js:1142
codePushUtil.js:41 [CodePush] An error occurred during sync. An error has occured while installing the package. Could not get the package start page. StackTrace: Error: An error has occured while installing the package. Could not get the package start page
    at preInstallFailure (file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/localPackage.js:246:41)
    at Object.callbackFromNative (file:///android_asset/www/cordova.js:295:52)
    at processMessage (file:///android_asset/www/cordova.js:1119:17)
    at processMessages (file:///android_asset/www/cordova.js:1142:9)
```

### Additional Information
```
<meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-eval' 'unsafe-inline' https://codepush.azurewebsites.net data: gap: cdvfile: https://ssl.gstatic.com 'unsafe-eval' 'unsafe-inline' https: http: wss: ws:; style-src 'self' 'unsafe-inline'; img-src * filesystem: cdvfile: data:; media-src * blob:" />
```

```
 <plugin name="https://github.com/apache/cordova-plugin-whitelist.git" spec="https://github.com/apache/cordova-plugin-whitelist.git"/>
        <plugin name="https://github.com/CocoonIO/cocoon-plugin-android-architecture.git" spec="https://github.com/CocoonIO/cocoon-plugin-android-architecture.git"/>
        <plugin name="https://github.com/apache/cordova-plugin-file.git#4.3.2" spec="https://github.com/apache/cordova-plugin-file.git#4.3.2"/>
        <plugin name="https://github.com/apache/cordova-plugin-file-transfer.git#1.7.1" spec="https://github.com/apache/cordova-plugin-file-transfer.git#1.7.1"/>
        <plugin name="https://github.com/MobileChromeApps/cordova-plugin-zip.git" spec="https://github.com/MobileChromeApps/cordova-plugin-zip.git"/>
        <plugin name="https://github.com/DavidGOrtega/tftest.git" spec="https://github.com/DavidGOrtega/tftest.git"/>
		<plugin name="https://github.com/apache/cordova-plugin-camera.git#2.4.x" spec="https://github.com/apache/cordova-plugin-camera.git#2.4.x"/>
		<plugin name="https://github.com/markmarijnissen/cordova-plugin-share.git" spec="https://github.com/markmarijnissen/cordova-plugin-share.git"/>
        <plugin name="https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin.git#5.2.1" spec="https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin.git#5.2.1"/>
		<plugin name="https://github.com/AlexDisler/cordova-plugin-inapppurchase.git" spec="https://github.com/AlexDisler/cordova-plugin-inapppurchase.git"/>
		<plugin name="https://github.com/pushandplay/cordova-plugin-apprate.git#v1.3.0" spec="https://github.com/pushandplay/cordova-plugin-apprate.git#v1.3.0"/>
		<plugin name="https://github.com/dpa99c/cordova-launch-review.git#3.1.0" spec="https://github.com/dpa99c/cordova-launch-review.git#3.1.0"/>
		<plugin name="https://github.com/Microsoft/appcenter-sdk-cordova.git#master:cordova-plugin-appcenter-shared" spec="https://github.com/Microsoft/appcenter-sdk-cordova.git#master:cordova-plugin-appcenter-shared"/>
        <plugin name="https://github.com/Microsoft/appcenter-sdk-cordova.git#master:cordova-plugin-appcenter-analytics" spec="https://github.com/Microsoft/appcenter-sdk-cordova.git#master:cordova-plugin-appcenter-analytics"/>
		<plugin name="https://github.com/Microsoft/appcenter-sdk-cordova.git#master:cordova-plugin-appcenter-crashes" spec="https://github.com/Microsoft/appcenter-sdk-cordova.git#master:cordova-plugin-appcenter-crashes"/>
        <plugin name="https://github.com/Microsoft/appcenter-sdk-cordova.git#master:cordova-plugin-appcenter-push" spec="https://github.com/Microsoft/appcenter-sdk-cordova.git#master:cordova-plugin-appcenter-push"/>
        <plugin name="https://github.com/Microsoft/cordova-plugin-code-push.git#master" spec="https://github.com/Microsoft/cordova-plugin-code-push.git#master"/>
        <plugin name="com.ludei.webviewplus.ios" spec="*"/>
		<plugin name="com.ludei.webviewplus.android" spec="*"/>
```

**Comment by alexandergoncharov** [comment]
Hi @DavidGOrtega,

Thanks for reporting!
Could you please clarify why do you think that the reason of issue is CSP?
And what exactly other configurations have you tried?

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @DavidGOrtega,

Are you still having this issue?

**Comment by alexandergoncharov** [comment]
Hi @DavidGOrtega,

I'm going to close this issue as I haven't heard in a while. Please feel free to reopen this issue if you will have questions or considerations.

Thanks,
Alexander
