### ISSUE TITLE
Hash missmatch after initial codepush - Differential updates

### ISSUE THREAD

**Issue by zafiredevelopment** [Microsoft/cordova-plugin-code-push#403]
### Description

When we are updating the app from a previous codepush (so release apk > codepush1> codepush2) we get an issue where the hash of the contents in the www folder is different than the computedHash on the service side.

```javascript
if (computedHash !== newUpdateHash) {
    errorCallback(new Error("The update contents failed the data integrity check."));
    return;
}
```

I will try to post more information soon if possible. Is there any way to disable diff updates? We are not using codepush.sync()

### Reproduction

1. Release apk or ipa (affects android and ios) and install on phone
2. Codepush deploy first version
3. Update the app
4. Codepush deploy second version - make sure you modify some files, the isDiffUpdate flag should be true and a partial diff update should be applied from this app update
5. Update the app - Update fails with Integrity check (see below for the exception)

### Additional Information
```javascript

codePushUtil.js:41 [CodePush]  The update contents failed the data integrity check.. StackTrace: Error: The update contents failed the data integrity check.
    at packageHashSuccess (file:///data/user/0/com.zafire./files/codepush/deploy/version…87c649/www/plugins/cordova-plugin-code-push/bin/www/localPackage.js:182:31)
    at Object.callbackFromNative (file:///data/user/0/com.zafire./files/codepush/deploy/version…1d059eeef2cbd0a73ff07140699828df6576f2b5eb124287c649/www/cordova.js:294:58)
    at <anonymous>:1:9
CodePushUtil.logError	@	codePushUtil.js:41
CodePushUtil.invokeErrorCallback	@	codePushUtil.js:45
installError	@	localPackage.js:43
verificationFail	@	localPackage.js:94
packageHashSuccess	@	localPackage.js:182
callbackFromNative	@	cordova.js:294
(anonymous function)	@	VM9338:1

```

* cordova-plugin-code-push version: 1.11.10
* List of installed plugins:
code-push 2.0.4 "CodePushAcquisition"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-appcenter-analytics 0.1.3 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.1.4 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.1.3 "App Center shared code for Cordova"
cordova-plugin-camera 4.0.1 "Camera"
cordova-plugin-code-push 1.11.10 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.7 "Globalization"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-vibration 2.1.5 "Vibration"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.1.1 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 7.0.1 "BarcodeScanner"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.0.7 "Launch Navigator"

* Cordova version: 7.1.0
* iOS/Android/Windows version: Android 6 and 7 and 8, iOS 11.3 and iOS 11.4
* Does this reproduce on a debug build or release build? All builds
* Does this reproduce on a simulator, or only on a physical device? Tested on a device - Not yet on an emulator

**Comment by zafiredevelopment** [comment]
We were uploading the zip manually from a curl POST request to the service and the diff update was pushing all the structure of the www with empty subfolders folders for the folders that had nothing changed inside them. I am not sure if that was the issue, we are now using the appcenter-cli for it and it works. Thanks
