### ISSUE TITLE
Failed to install 'cordova-plugin-code-push': Error: Expected plugin to have ID "cordova-plugin-dialogs" but got "code-push".

### ISSUE THREAD

**Issue by jpike88** [Microsoft/cordova-plugin-code-push#419]
When attempting to install with code-push:"^2.0.4" in package.json, this causes an issue, as cordova-plugin-dialog has an issue resolving it, throwing the error:

`Failed to install 'cordova-plugin-code-push': Error: Expected plugin to have ID "cordova-plugin-dialogs" but got "code-push".
    at checkID (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:215:15)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:199:9
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at process._tickCallback (internal/process/next_tick.js:112:11)
Failed to restore plugin "cordova-plugin-code-push" from config.xml. You might need to try adding it again. Error: Error: Expected plugin to have ID "cordova-plugin-dialogs" but got "code-push".
`

The issue is in detail here:

https://issues.apache.org/jira/browse/CB-13797?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=16504597#comment-16504597

I have attached a PR upgrading to code-push@2.0.5 to resolve this issue.

**Comment by alexandergoncharov** [comment]
Hi @jpike88 ,
Thanks for reporting and sorry for long delay.

I tested your PR and merged it.
Thanks for contributing!

Please feel free to reopen it if you'll have any questions.

Thanks,
Alexander

**Comment by szh** [comment]
I'm getting this error with plugin version 1.12.0
