### ISSUE TITLE
Error downloading package - javax.net.ssl.SSLProtocolException

### ISSUE THREAD

**Issue by renanvasconcelos** [Microsoft/cordova-plugin-code-push#515]
### Description

Try to sync code-push version and get a null error no file-transfer plugin. 

This is the exception I get on my console:
```
[CodePush]  null. StackTrace: Error: null
    at downloadError (file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/remotePackage.js:65:54)
    at fail (file:///android_asset/www/plugins/cordova-plugin-file-transfer/www/FileTransfer.js:226:9)
    at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:293:52)
    at <anonymous>:1:9 codePushUtil.js:41
[CodePush] An error occurred during sync. null. StackTrace: Error: null
    at downloadError (file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/remotePackage.js:65:54)
    at fail (file:///android_asset/www/plugins/cordova-plugin-file-transfer/www/FileTransfer.js:226:9)
    at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:293:52)
    at <anonymous>:1:9 

```
Using Chrome debug mode shows that I'm facing this exception:
```
javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x77cb52b0: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x68917ec8:0x00000000)
```

Found a similar issue on react-native plugin [here ](https://github.com/Microsoft/react-native-code-push/issues/1546)

### Reproduction

Create an Ionic 3 project and try to update app using code-push.

Code bellow:

```
let subscription = this.codepush.sync({}, (progress) => {
      console.log('Progresso',progress);
    }).subscribe((status) => {
      console.log('Status',status);
      if (status == SyncStatus.CHECKING_FOR_UPDATE && !silent)
        this.showLoading('Verificando atualizações');
      else if (status == SyncStatus.DOWNLOADING_PACKAGE)
        this.showLoading('Fazendo download de atualização')
      else if (status == SyncStatus.IN_PROGRESS)
        this.showLoading('Atualização em progresso')
      else if (status == SyncStatus.INSTALLING_UPDATE)
        this.showLoading('Instalando atualização')
      else if (status == SyncStatus.UP_TO_DATE && !silent) {
        alert('Sem atualizações');
        this.loading.dismissAll();
      }
      else if (status == SyncStatus.UPDATE_INSTALLED) {
        this.showLoading('Aplicativo atualizado')
      }
      else if (status == SyncStatus.ERROR) {
        alert('Ocorreu um erro durante a atualização.');
      } else {
        console.log('Status codepush',status);
      }
    },
    (error) => {
      console.log('Erro ao atulizar',error);
      this.loading.dismissAll();
      alert('Ocorreu um erro durante a atualização.');
    });
```

### Additional Information

* cordova-plugin-code-push version: ^1.11.12
* List of installed plugins:
code-push 2.0.6 "CodePushAcquisition"
cordova-open-native-settings 1.5.1 "Native settings"
cordova-plugin-android-wifi-manager 1.0.0 "Android WifiManager"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-code-push 1.11.12 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
es6-promise-plugin 4.1.0 "Promise"
wifiwizard2 3.1.0 "WifiWizard2"
* Cordova version: 7.0.0
* iOS/Android/Windows version:
Android 4.4.4 (Upgrade not possible)
* Device
Physical SM-T560

![image](https://user-images.githubusercontent.com/20398811/55002433-5b3e5f80-4fb5-11e9-8440-8bcbb6f7fe10.png)

![image](https://user-images.githubusercontent.com/20398811/55002485-6e512f80-4fb5-11e9-9b83-f25e16e7bd44.png)

It's not possible to update my application without code-push. I have 2250 devices all around the country that are not connected to google services and are now using kiosk mode. The only way I have to update them is code-push. So thats's really urgent.

Thanks for any help.

**Comment by alexandergoncharov** [comment]
Hi @renanvasconcelos ,
Thanks for reporting and sorry for this issue.

Could you please describe can you confirm that this issue only for Android 4.x.x? Other Android device versions work correct?

**Comment by renanvasconcelos** [comment]
@alexandergoncharov Yes! Just tried with API25 and it's working like a charm.

It seems we have an Infrastructure issue here. Something realted to Azure and SSLv3. That's scaring my off. I have 2200 devices running all over the country and I can't update them without codepush.

**Comment by renanvasconcelos** [comment]
Hello @alexandergoncharov.

Any update about it?

**Comment by alexandergoncharov** [comment]
Hi @renanvasconcelos,
Sorry for this delay.

We are working on fixing this issue on Azure side. I'll be keep you posted. Sorry for this issue.

**Comment by ahmedNY** [comment]
Any new update, I got the same error while testing my app on an emulator of android 4.4.2

**Comment by renanvasconcelos** [comment]
Any update about it?

**Comment by botatoes** [comment]
Hi, we are currently working on the next version of CodePush (no breaking changes) that will fix a bunch of the bugs people are seeing. We will come back and confirm this is fixed with the changes once we are done.

**Comment by 987094257** [comment]
@renanvasconcelos Hi, I have the same problem. Have you solved it?

**Comment by renanvasconcelos** [comment]
> @renanvasconcelos Hi, I have the same problem. Have you solved it?

No. It's in the thread that they are working on a fix.

**Comment by Joel619** [comment]
Hi, any updates?

**Comment by seme1** [comment]
Fives months already since this was reported and still no updates from your side or even a temporary work-around ?

**Comment by bbialas** [comment]
Hi, any news...?

**Comment by ludufre** [comment]
This was fixed in the latest version. At least with me it doesn't happen anymore
