### ISSUE TITLE
cordova code-push not working with crypt file

### ISSUE THREAD

**Issue by yadujaryal** [microsoft/cordova-plugin-code-push#544]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

cordova code-push working fine but after using cordova crypt-file plugin. code-push stopped working , for me both plugins are important.

### Reproduction

enzVLoisNbk:APA91bGURKRI3fRX8PJydbcNMXqrDmZ-HwoV7LIgB8fNbH0cAMhVtyl78PBJdVqSTt_H02IlsFPl7WEBdnQ1Amd_8h5e7RdvOr8-nqs1f4GZrTRIIB_Ia7PnU99CZGmRwdZZkv2um9f4
custom.js:671 Refresh to get new token: enzVLoisNbk:APA91bGURKRI3fRX8PJydbcNMXqrDmZ-HwoV7LIgB8fNbH0cAMhVtyl78PBJdVqSTt_H02IlsFPl7WEBdnQ1Amd_8h5e7RdvOr8-nqs1f4GZrTRIIB_Ia7PnU99CZGmRwdZZkv2um9f4
plugins/cordova-plugin-code-push/bin/www/codePushUtil.js:36 [CodePush] Checking for update.
plugins/cordova-plugin-code-push/bin/www/codePushUtil.js:36 [CodePush] An update is available. {"appVersion":"1.2.4","deploymentKey":"
984ac644f47d","description":"","downloadUrl":"https://codepushupdates.azureedge.net/storagev2/G0-kdm47xga2zlKrx8ewRUyRez1Tb1e864cd-18c7-47d6-85c6-984ac644f47d","isMandatory":false,"label":"v9","packageHash":"b19aa57f158d22844f264ffe48f7a360d33698d249b2e99a14f1f848eb31aba6","packageSize":2984897,"failedInstall":false}
plugins/cordova-plugin-code-push/bin/www/codePushUtil.js:36 [CodePush] Downloading update
plugins/cordova-plugin-code-push/bin/www/codePushUtil.js:36 [CodePush] Package download success: {"deploymentKey":"P3qaz7Ieazmrg7ciYIec7LJq5zrMb1e864cd-18c7-47d6-85c6-984ac644f47d","description":"","label":"v9","appVersion":"1.2.4","isMandatory":false,"packageHash":"b19aa57f158d22844f264ffe48f7a360d33698d249b2e99a14f1f848eb31aba6","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/files/codepush/download/update.zip"}
plugins/cordova-plugin-code-push/bin/www/codePushUtil.js:36 [CodePush] Installing update
plugins/cordova-plugin-code-push/bin/www/codePushUtil.js:36 [CodePush] Applying full update
plugins/cordova-plugin-code-push/bin/www/codePushUtil.js:41 [CodePush] Preinstall failure. Could not get the package start page
CodePushUtil.logError @ plugins/cordova-plugin-code-push/bin/www/codePushUtil.js:41
plugins/cordova-plugin-code-push/bin/www/codePushUtil.js:41 [CodePush]  An error has occured while installing the package. Could not get the package start page. StackTrace: Error: An error has occured while installing the package. Could not get the package start page
    at preInstallFailure (file:///android_asset/www/+++/plugins/cordova-plugin-code-push/bin/www/localPackage.js:246:41)
    at Object.callbackFromNative (file:///android_asset/www/+++/cordova.js:290:52)
    at processMessage (file:///android_asset/www/+++/cordova.js:1101:17)
    at processMessages (file:///android_asset/www/+++/cordova.js:1124:9)
CodePushUtil.logError @ plugins/cordova-plugin-code-push/bin/www/codePushUtil.js:41
plugins/cordova-plugin-code-push/bin/www/codePushUtil.js:41 [CodePush] An error occurred during sync. An error has occured while installing the package. Could not get the package start page. StackTrace: Error: An error has occured while installing the package. Could not get the package start page
    at preInstallFailure (file:///android_asset/www/+++/plugins/cordova-plugin-code-push/bin/www/localPackage.js:246:41)
    at Object.callbackFromNative (file:///android_asset/www/+++/cordova.js:290:52)
    at processMessage (file:///android_asset/www/+++/cordova.js:1101:17)
    at processMessages (file:///android_asset/www/+++/cordova.js:1124:9)
CodePushUtil.logError @ plugins/cordova-plugin-code-push/bin/www/codePushUtil.js:41

### Additional Information

* cordova-plugin-code-push version: 1.11.19
* List of installed plugins:code-push 2.0.6 "CodePushAcquisition"
cordova-open 1.0.12 "Open"
cordova-pdf-generator 2.0.8 "PDFGenerator"
cordova-plugin-admobpro 2.35.3 "AdMob Plugin Pro"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-code-push 1.11.19 "CodePush"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-extension 1.5.4 "Cordova Plugin Extension"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-fileopener 1.0.5 "FileOpener"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-spinner 1.1.0 "Spinner Plugin"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"

* Cordova version:9.0.0 (cordova-lib@9.0.1)
* iOS/Android/Windows version: Android
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? physical device

(The more info the faster we will be able to address it!)
working fine without file-crypt plugin

**Comment by SamarBakr** [comment]
Any updates ? I'm facing same issue #72   , Is there any alternative plugin for cordova-plugin-crypt-file that is compatible with Code-Push?

**Comment by yadujaryal** [comment]
No there is no any compatible plugins..
