### ISSUE TITLE
codepush android - An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by jacksonkr** [microsoft/cordova-plugin-code-push#648]
### Description

On android, codepush fetches and downloads the newest code from appcenter but crashes when unpacking the code to the device

### Reproduction

N/A

### Additional Information

* cordova-plugin-code-push version: 1.13.1
* List of installed plugins:
```
code-push 3.0.1 "CodePushAcquisition"
cordova-plugin-advanced-http 3.0.1 "Advanced HTTP plugin"        
cordova-plugin-appcenter-analytics 0.3.6 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.3.6 "App Center Crashes for Cordova"
cordova-plugin-appcenter-push 0.3.6 "App Center Push for Cordova"cordova-plugin-appcenter-shared 0.3.6 "App Center shared code for Cordova"
cordova-plugin-code-push 1.13.1 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-facebook4 6.4.0 "Facebook Connect"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-sign-in-with-apple 0.1.2 "cordova-plugin-sign-in-with-apple"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine" 
cordova-plugin-wkwebviewxhrfix 0.1.0 "WKWebView XHR Fix"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
```
* Cordova version: 9.0.0 (cordova-lib@9.0.1)
* iOS/Android/Windows version: Android 10 (QQ2A.200305.002)
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? Physical: Pixel 2

** Logcat Stack Trace form Android Studio **

```
2020-08-31 17:39:27.131 27051-27112/com.thecompany.theproject.android E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #6Process: com.thecompany.theproject.android, PID: 27051java.lang.RuntimeException: An error occurred while executing doInBackground()at android.os.AsyncTask$4.done(AsyncTask.java:399)at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)at java.util.concurrent.FutureTask.setException(FutureTask.java:252)at java.util.concurrent.FutureTask.run(FutureTask.java:271)at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)at java.lang.Thread.run(Thread.java:919)Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/nimbusds/jose/util/Base64;at com.nimbusds.jwt.SignedJWT.parse(SignedJWT.java:110)at com.microsoft.cordova.CodePush.verifyAndDecodeJWT(CodePush.java:174)at com.microsoft.cordova.CodePush.access$100(CodePush.java:39)at com.microsoft.cordova.CodePush$1.doInBackground(CodePush.java:133)at com.microsoft.cordova.CodePush$1.doInBackground(CodePush.java:115)at android.os.AsyncTask$3.call(AsyncTask.java:378)at java.util.concurrent.FutureTask.run(FutureTask.java:266)at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: com.nimbusds.jose.util.Base64at java.lang.VMClassLoader.findLoadedClass(Native Method)at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)at java.lang.ClassLoader.loadClass(ClassLoader.java:363)at java.lang.ClassLoader.loadClass(ClassLoader.java:312)at com.nimbusds.jwt.SignedJWT.parse(SignedJWT.java:110)
at com.microsoft.cordova.CodePush.verifyAndDecodeJWT(CodePush.java:174)
at com.microsoft.cordova.CodePush.access$100(CodePush.java:39)
at com.microsoft.cordova.CodePush$1.doInBackground(CodePush.java:133)
at com.microsoft.cordova.CodePush$1.doInBackground(CodePush.java:115)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lnet/minidev/json/JSONAware;at com.nimbusds.jwt.SignedJWT.parse(SignedJWT.java:110)
at com.microsoft.cordova.CodePush.verifyAndDecodeJWT(CodePush.java:174)
at com.microsoft.cordova.CodePush.access$100(CodePush.java:39)
at com.microsoft.cordova.CodePush$1.doInBackground(CodePush.java:133)
at com.microsoft.cordova.CodePush$1.doInBackground(CodePush.java:115)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: Didn't find class "net.minidev.json.JSONAware" on path: DexPathList[[zip file "/data/app/com.thecompany.theproject.android-16QuIFfjNmZKfGyx5CbWrA==/base.apk"],nativeLibraryDirectories=[/data/app/com.thecompany.theproject.android-16QuIFfjNmZKfGyx5CbWrA==/lib/arm64, /system/lib64, /system/product/lib64]]at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)at java.lang.ClassLoader.loadClass(ClassLoader.java:379)at java.lang.ClassLoader.loadClass(ClassLoader.java:312)at com.nimbusds.jwt.SignedJWT.parse(SignedJWT.java:110)
at com.microsoft.cordova.CodePush.verifyAndDecodeJWT(CodePush.java:174)
at com.microsoft.cordova.CodePush.access$100(CodePush.java:39)
at com.microsoft.cordova.CodePush$1.doInBackground(CodePush.java:133)
at com.microsoft.cordova.CodePush$1.doInBackground(CodePush.java:115)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
```

**Comment by rooneyl** [comment]
Same issue here. 
related to #613

**Comment by jacksonkr** [comment]
@rooneyl My solution was downgrading to `cordova-plugin-code-push@1.12.1`

https://github.com/microsoft/cordova-plugin-code-push/issues/613#issuecomment-631639540
